### ISSUE TITLE
Package form - exception in User interaction

### ISSUE THREAD

**Issue by mohierf** [fusioninventory/fusioninventory-for-glpi#2413]
![image](https://user-images.githubusercontent.com/2932687/34574281-3a76b9a2-f177-11e7-8b60-4e391356418b.png)

```
Fatal error: Uncaught Error: Class 'PluginFusioninventoryDeployUserinteraction' not found in /var/www/html/glpi/plugins/fusioninventory/inc/deploypackage.class.php:569 Stack trace: #0 /var/www/html/glpi/plugins/fusioninventory/inc/deployinstall.class.php(101): 

PluginFusioninventoryDeployPackage->displayOrderTypeForm() #1 /var/www/html/glpi-fiducial/inc/commonglpi.class.php(482): 

PluginFusioninventoryDeployinstall::displayTabContentForItem(Object(PluginFusioninventoryDeployPackage), '1', '') #2 /var/www/html/glpi/ajax/common.tabs.php(96): 

CommonGLPI::displayStandardTab(Object(PluginFusioninventoryDeployPackage), 'PluginFusioninv...', '', Array) #3 {main} thrown in /var/www/html/glpi/plugins/fusioninventory/inc/deploypackage.class.php on line 569
```

**Comment by wawax** [comment]
which branch are you using ? looks like the class UserInteraction is missing, which seems very strange as the file is present in the repository

**Comment by mohierf** [comment]
9.2+1.0

**Comment by mohierf** [comment]
Forget this, I did some mistake on my testing environment 😞
