### ISSUE TITLE
Error on upgrade 

### ISSUE THREAD

**Issue by camlafit** [fusioninventory/fusioninventory-for-glpi#2553]
Hello

In dev instance (glpi 9.3 RC1 and fusioninventory glpi took from master : 1d3ea42530f5d0253b24a71a0775551d61233471)

``` 
PHP Warning: rename(/var/www/glpi/files/_plugins/fusinvdeploy/files,/var/www/glpi/files/_plugins/fusioninventory/files): Directory not empty in /var/www/glpi/plugins/fusioninventory/install/update.php at line 296

Fatal error: Uncaught RuntimeException: Cannot run an UPDATE query without WHERE clause! in /var/www/glpi/inc/dbmysql.class.php:973 Stack trace: #0 /var/www/glpi/inc/dbmysql.class.php(1001): DBmysql->buildUpdate('glpi_plugin_fus...', Array, Array) #1 /var/www/glpi/plugins/fusioninventory/install/update.php(1613): DBmysql->update('glpi_plugin_fus...', Array, Array) #2 /var/www/glpi/plugins/fusioninventory/install/update.php(364): do_entities_migration(Object(Migration)) #3 /var/www/glpi/plugins/fusioninventory/hook.php(825): pluginFusioninventoryUpdate('9.2+1.0', 'Migration') #4 /var/www/glpi/inc/plugin.class.php(701): plugin_fusioninventory_install() #5 /var/www/glpi/front/plugin.form.php(47): Plugin->install('3') #6 {main} thrown in /var/www/glpi/inc/dbmysql.class.php on line 97
```

**Comment by camlafit** [comment]
Ok  understood 

glpi project reject any update without any where condition : 
https://github.com/glpi-project/glpi/blob/9.3-RC1/inc/dbmysql.class.php#L972

**Comment by Wolvverine** [comment]
now from master branch:

2018-06-05T11:15:49.044204566Z 10.0.0.67 - - [05/Jun/2018:11:15:49 +0000] "POST /front/plugin.form.php HTTP/1.1" 200 25841 "http://docker:80/front/plugin.php" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"
2018-06-05T11:15:49.046472105Z 2018/06/05 11:15:49 [error] 25#25: *31441 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Cannot run an UPDATE query without WHERE clause!' in /var/www/inc/dbmysql.class.php:973
2018-06-05T11:15:49.046539351Z Stack trace:
2018-06-05T11:15:49.046561238Z #0 /var/www/plugins/fusioninventory/install/update.php(4590): DBmysql->buildUpdate('glpi_networkequ...', Array)
2018-06-05T11:15:49.046578684Z #1 /var/www/plugins/fusioninventory/install/update.php(426): do_networkequipment_migration(Object(Migration))
2018-06-05T11:15:49.046594967Z #2 /var/www/plugins/fusioninventory/hook.php(825): pluginFusioninventoryUpdate('9.3+1.0', 'Migration')
2018-06-05T11:15:49.046611160Z #3 /var/www/inc/plugin.class.php(701): plugin_fusioninventory_install()
2018-06-05T11:15:49.046627040Z #4 [internal function]: Plugin->install('1')
2018-06-05T11:15:49.046642907Z #5 /var/www/front/plugin.form.php(47): call_user_func(Array, '1')
2018-06-05T11:15:49.046658659Z #6 {main}
2018-06-05T11:15:49.046682724Z   thrown in /var/www/inc/dbmysql.class.php on line 973" while reading upstream, client: xx.xx.xx.xx, server: , request: "POST /front/plugin.form.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm5.sock:", host: "docker:80", referrer: "http://docker:80/front/plugin.php"

**Comment by trasher** [comment]
See https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2556
