### ISSUE TITLE
Unmanaged devices: import information

### ISSUE THREAD

**Issue by Megachip** [fusioninventory/fusioninventory-for-glpi#2633]
thrown an error:

```
Fatal error: Uncaught Error: Call to a member function showDownloadInventoryFile() on boolean in /usr/share/glpi/plugins/fusioninventory/inc/rulematchedlog.class.php:230 Stack trace: #0 /usr/share/glpi/plugins/fusioninventory/inc/rulematchedlog.class.php(167): PluginFusioninventoryRulematchedlog->showForm('336', 'PluginFusioninv...') #1 /usr/share/glpi/inc/commonglpi.class.php(482): PluginFusioninventoryRulematchedlog::displayTabContentForItem(Object(PluginFusioninventoryUnmanaged), '1', '') #2 /usr/share/glpi/ajax/common.tabs.php(96): CommonGLPI::displayStandardTab(Object(PluginFusioninventoryUnmanaged), 'PluginFusioninv...', '', Array) #3 {main} thrown in /usr/share/glpi/plugins/fusioninventory/inc/rulematchedlog.class.php on line 230
```

GLPI 9.2.4
FI 9.2+2.0

**Comment by AnaelMobilia** [comment]
@Megachip 
Could you, please, provide the full error message (not just a Screenshot) ?
Which version are you using ?

Regards,
Anael

**Comment by toehold** [comment]
Same error using:
GLPI 9.3.1
FusionInventory 9.3+1.1

when clicking on the Import Information on an unmanaged device (printer).

[php7:error] [pid 31240] [client 10.10.65.0:44146] PHP Fatal error:  Uncaught Error: Call to a member function showDownloadInventoryFile() on boolean in /var/www/html/glpi/plugins/fusioninventory/inc/rulematchedlog.class.php:226\nStack trace:\n#0 /var/www/html/glpi/plugins/fusioninventory/inc/rulematchedlog.class.php(164): PluginFusioninventoryRulematchedlog->showForm('59', 'PluginFusioninv...')\n#1 /var/www/html/glpi/inc/commonglpi.class.php(488): PluginFusioninventoryRulematchedlog::displayTabContentForItem(Object(PluginFusioninventoryUnmanaged), '1', '')\n#2 /var/www/html/glpi/ajax/common.tabs.php(92): CommonGLPI::displayStandardTab(Object(PluginFusioninventoryUnmanaged), 'PluginFusioninv...', '', Array)\n#3 {main}\n  thrown in /var/www/html/glpi/plugins/fusioninventory/inc/rulematchedlog.class.php on line 226, referer: http://10.7.20.163/glpi/plugins/fusioninventory/front/unmanaged.form.php?id=59

**Comment by kotryakhov** [comment]
> Same error using:
> GLPI 9.3.1
> FusionInventory 9.3+1.1
> 
> when clicking on the Import Information on an unmanaged device (printer).
> 
> [php7:error] [pid 31240] [client 10.10.65.0:44146] PHP Fatal error: Uncaught Error: Call to a member function showDownloadInventoryFile() on boolean in /var/www/html/glpi/plugins/fusioninventory/inc/rulematchedlog.class.php:226\nStack trace:\n#0 /var/www/html/glpi/plugins/fusioninventory/inc/rulematchedlog.class.php(164): PluginFusioninventoryRulematchedlog->showForm('59', 'PluginFusioninv...')\n#1 /var/www/html/glpi/inc/commonglpi.class.php(488): PluginFusioninventoryRulematchedlog::displayTabContentForItem(Object(PluginFusioninventoryUnmanaged), '1', '')\n#2 /var/www/html/glpi/ajax/common.tabs.php(92): CommonGLPI::displayStandardTab(Object(PluginFusioninventoryUnmanaged), 'PluginFusioninv...', '', Array)\n#3 {main}\n thrown in /var/www/html/glpi/plugins/fusioninventory/inc/rulematchedlog.class.php on line 226, referer: http://10.7.20.163/glpi/plugins/fusioninventory/front/unmanaged.form.php?id=59
> 
> If I comment out this 2 lines in /var/www/html/glpi/plugins/fusioninventory/inc/rulematchedlog.class.php
> 
> #$class = PluginFusioninventoryItem::getFIItemClassInstance($itemtype);
> #$class->showDownloadInventoryFile($items_id);
> 
> it works!

This is not Jedi's way ;-)
The right way is to chek whether ClassInstance was returned as class or bool 
      $class = PluginFusioninventoryItem::getFIItemClassInstance($itemtype);
      if ($class) {
         $class->showDownloadInventoryFile($items_id);
      }
