### ISSUE TITLE
Deploy Package Management: package actions broken

### ISSUE THREAD

**Issue by TheRich-71** [fusioninventory/fusioninventory-for-glpi#2795]
Hi everyone,
after upgrading glpi and fusioninventory to 9.4, I am not able to view or modify previously created package actions. From apache error log, I see:

> PHP Fatal error:  Uncaught Error: Call to undefined method Html::checkAllAsCheckbox() in /var/www/glpi/plugins/fusioninventory/inc/deployfile.class.php:237\nStack trace:\n#0 /var/www/glpi/plugins/fusioninventory/inc/deploypackage.class.php(594): PluginFusioninventoryDeployFile->displayList(Object(PluginFusioninventoryDeployPackage), Array, 2132236272)\n#1 /var/www/glpi/plugins/fusioninventory/inc/deployinstall.class.php(99): PluginFusioninventoryDeployPackage->displayOrderTypeForm()\n#2 /var/www/glpi/inc/commonglpi.class.php(485): PluginFusioninventoryDeployinstall::displayTabContentForItem(Object(PluginFusioninventoryDeployPackage), '1', '')\n#3 /var/www/glpi/ajax/common.tabs.php(92): CommonGLPI::displayStandardTab(Object(PluginFusioninventoryDeployPackage), 'PluginFusioninv...', '', Array)\n#4 {main}\n  thrown in /var/www/glpi/plugins/fusioninventory/inc/deployfile.class.php on line 237, referer: https://***/glpi/plugins/fusioninventory/front/deploypackage.form.php?id=42

Any idea what has happened?

**Comment by TheRich-71** [comment]
Gets a bit more weird: Opening packages, which are currently used by deploy tasks, I can view the package actions, but all files uploaded previously show the following comment:
> This file is not correctly registered in database.
You can fix it by uploading or selecting the good one.
Any help or comment appreciated...

**Comment by TheRich-71** [comment]
Okay, solved. Just included the fixes from #2762, and issues are gone...
